type ProjectToken @entity {
  id: ID!
  name: String!
  symbol: String!
  decimals: Int!
  address: Bytes!
  updatedAt: BigInt!
  isDepositPaused: Boolean
  isWithdrawPaused: Boolean
  depositedAmount: BigDecimal
  lvr: BigDecimal
  pitAmount: BigDecimal
  depositingLevelAmount: BigDecimal
  currentDepositingLevel: BigDecimal
  underlyingTokens: [ERC20Token!]
}

type LendingToken @entity {
  id: ID!
  name: String!
  symbol: String!
  decimals: Int!
  address: Bytes!
  updatedAt: BigInt!
  isPaused: Boolean
  borrowingLevelAmount: BigDecimal
  fTokenAddress: Bytes!
  underlyingTokens: [ERC20Token!]
}

type ERC20Token @entity {
  id: ID!
  name: String!
  symbol: String!
  decimals: Int!
  address: Bytes!
  linksNumber: BigDecimal
}

type BorrowLog @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  asset: String!
  type: String!
  date: BigInt!
  userAddress: Bytes!
}

type CollateralDepositedHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  date: BigInt!
}

type PITTokenHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  date: BigInt!
}

type OutstandingHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  date: BigInt!
}

type LenderAPYHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  date: BigInt!
}

type BorrowingAPYHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  date: BigInt!
}

type LenderAggregateCapitalDepositedHistory @entity(immutable: true) {
  id: ID!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  date: BigInt!
}

type TotalState @entity {
  id: ID!
  type: String!
  amount: BigDecimal!
  lendingTokenAddress: Bytes
  updatedAt: BigInt!
}

type UserState @entity {
  id: ID!
  userAddress: Bytes
  updatedAt: BigInt!
  tokenAddresses: [User!]
}

type BorrowedState @entity {
  id: ID!
  lendingTokenAddress: Bytes
  updatedAt: BigInt!
  userAddresses: [User!]
}

type User @entity {
  id: ID!
  address: Bytes!
  tokenAddress: Bytes!
  updatedAt: BigInt!
  borrowedAmount: BigDecimal
  outstandingAmount: BigDecimal
  depositedAmount: BigDecimal
}

type LeveragePositionData @entity {
  id: ID!
  borrowerAddress: PositionByUser!
  prjToken: String!
  prjTokenPrice: BigDecimal!
  longAsset: Bytes!
  lendingToken: String!
  lendingTokenPrice: BigDecimal!
  shortAsset: Bytes!
  longCount: BigDecimal!
  shortCount: BigDecimal!
  exposureAmount: BigDecimal!
  leverageType: Int!
  projectTokenRefId: PositionByProjectToken!
  lendingTokenRefId: PositionByLendingToken!
  date: BigInt!
}

type LongAssetCountState @entity {
  id: ID!
  currentTotalLongAssetCount: BigDecimal!
  maxTotalLongAssetCount: BigDecimal!
}

type ShortAssetCountState @entity {
  id: ID!
  closeShortAmount: BigDecimal!
  currentTotalShortAssetCount: BigDecimal!
  maxTotalShortAssetCount: BigDecimal!
}

type PositionByProjectToken @entity(immutable: true) {
  id: ID!
  positions: [LeveragePositionData!]! @derivedFrom(field: "projectTokenRefId")
} 

type PositionByLendingToken @entity(immutable: true) {
  id: ID!
  positions: [LeveragePositionData!]! @derivedFrom(field: "lendingTokenRefId")
} 

type PositionByUser @entity(immutable: true) { 
  id: ID!
  positions: [LeveragePositionData!]! @derivedFrom(field: "borrowerAddress")
}